<template>
<ul class="messages" v-chat-scroll>
  <li class="message" v-for="(n, index) in messages" :key="index">{{ n }}</li>
</ul>
</template>
<script>
export default {
    name: 'testScroll',
    data(){
        return {messages:[
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !",
            "Hello There !"
        ]}
    }
}
</script>