export default {
    get_business_ownership_types()
    {
        return [
            {
                "code": "GOVT",
                "name": "Government"
            },
            {
                "code": "INDIVSOLE",
                "name": "Sole Proprietor"
            },
            {
                "code": "LLC",
                "name": "LLC"
            },
            {
                "code": "NONPRFT",
                "name": "Non-Profit Org"
            },
            {
                "code": "PRTNRSHP",
                "name": "Partnership"
            },
            {
                "code": "PRIVCORP",
                "name": "Private Corporation"
            },
            {
                "code": "PUBCORP",
                "name": "Public Corporation"
            },
            {
                "code": "TAXEXMPT",
                "name": "Tax Exempt"
            }
        ]; //end ownership type
       
       
    },
    get_business_titles()
    {
        return [
            {
                "code": "OWNER",
                "name": "Owner"
            },
            {
                "code": "PRESIDENT",
                "name": "President"
            },
            {
                "code": "CEO",
                "name": "CEO"
            },
            {
                "code": "CFO",
                "name": "CFO"
            },
            {
                "code": "SECRETARY",
                "name": "Secretary"
            },
            {
                "code": "PARTNER",
                "name": "Partner"
            },
            {
                "code": "TREASURER",
                "name": "Treasurer"
            } 
        ]; //end title type
    },
    get_mcc_array()
    {
        return [
        { code: '0742', name: 'Veterinary Services'},
        { code: '0763', name: 'Agricultural Co-operatives'},
        { code: '0780', name: 'Landscaping and Horticultural Services'},
        { code: '1520', name: 'General Contractors - Residential and Commercial'},
        { code: '1711', name: 'Heating, Plumbing, and Air Conditioning Contractors'},
        { code: '1731', name: 'Electrical Contractors'},
        { code: '1740', name: 'Masonry, Stonework, Tile Setting, Plastering and Insulation Contractors'},
        { code: '1750', name: 'Carpentry Contractors'},
        { code: '1761', name: 'Roofing, Siding, and Sheet Metal Work Contractors'},
        { code: '1771', name: 'Concrete Work Contractors'},
        { code: '1799', name: 'Special Trade Contractors (Not Elsewhere Classified)'},
        { code: '2741', name: 'Miscellaneous Publishing and Printing u'},
        { code: '2791', name: 'Typesetting, Plate Making and Related Services u'},
        { code: '2842', name: 'Specialty Cleaning, Polishing and Sanitation Preparations u'},
        /* Airlines removed */
        { code: '3351', name: 'AFFILIATED AUTO RENTAL'},
        /* Specific hotels/motels removed*/
        { code: '4011', name: 'Railroads'},
        { code: '4111', name: 'Local and Suburban Commuter Passenger Transportation, including Ferries'},
        { code: '4112', name: 'Passenger Railways'},
        { code: '4119', name: 'Ambulance Services'},
        { code: '4121', name: 'Taxicabs and Limousines'},
        { code: '4131', name: 'Bus Lines'},
        { code: '4214', name: 'Motor Freight Carriers and Trucking - Local and Long Distance, Moving and Storage Companies, and Local Delivery Services'},
        { code: '4215', name: 'Courier Services - Air and Ground, and Freight Forwarders'},
        { code: '4225', name: 'Public Warehousing and Storage - Farm Products, Refrigerated Goods, Household Goods, and Storage'},
        { code: '4411', name: 'Steamship and Cruise Lines'},
        { code: '4457', name: 'Boat Rentals and Leasing'},
        { code: '4468', name: 'Marinas, Marine Service, and Supplies'},
        { code: '4511', name: 'Airlines and Air Carriers (Not Elsewhere Classified)'},
        { code: '4582', name: 'Airports, Flying Fields, and Airport Terminals'},
        { code: '4722', name: 'Travel Agencies and Tour Operators'},
        { code: '4723', name: 'Package Tour Operators - Germany Only'},
        { code: '4784', name: 'Tolls and Bridge Fees'},
        { code: '4789', name: 'Transportation Services (Not Elsewhere Classified)'},
        { code: '4812', name: 'Telecommunication Equipment and Telephone Sales'},
        { code: '4814', name: 'Telecommunication Services, including Local and Long Distance Calls, Credit Card Calls, Calls Through Use of Magnetic Stripe Reading Telephones, and Fax Services'},
        { code: '4816', name: 'Computer Network/Information Services'},
        { code: '4821', name: 'Telegraph Services'},
        { code: '4829', name: 'Wire Transfer Money Orders (WTMOs)'},
        { code: '4899', name: 'Cable, Satellite, and Other Pay Television/Radio Services'},
        { code: '4900', name: 'Utilities - Electric, Gas, Water, Sanitary'},
        { code: '5013', name: 'Motor Vehicle Supplies and New Parts u'},
        { code: '5021', name: 'Office and Commercial Furniture u'},
        { code: '5039', name: 'Construction Materials (Not Elsewhere Classified) u'},
        { code: '5044', name: 'Photographic, Photocopy, Microfilm Equipment and Supplies u'},
        { code: '5045', name: 'Computers and Computer Peripheral Equipment and Software u'},
        { code: '5046', name: 'Commercial Equipment (Not Elsewhere Classified) u'},
        { code: '5047', name: 'Medical, Dental, Ophthalmic and Hospital Equipment and Supplies u'},
        { code: '5051', name: 'Metal Service Centers and Offices u'},
        { code: '5065', name: 'Electrical Parts and Equipment u'},
        { code: '5072', name: 'Hardware, Equipment and Supplies u'},
        { code: '5074', name: 'Plumbing and Heating Equipment and Supplies u'},
        { code: '5085', name: 'Industrial Supplies (Not Elsewhere Classified) u'},
        { code: '5094', name: 'Precious Stones and Metals, Watches and Jewelry u'},
        { code: '5099', name: 'Durable Goods (Not Elsewhere Classified) u'},
        { code: '5111', name: 'Stationery, Office Supplies, Printing and Writing Paper u'},
        { code: '5122', name: 'Drugs, Drug Proprietaries, and Druggist Sundries u'},
        { code: '5131', name: 'Piece Goods, Notions, and Other Dry Goods u'},
        { code: '5137', name: 'Men\'s, Women\'s, and Children\'s Uniforms and Commercial Clothing'},
        { code: '5139', name: 'Commercial Footwear u'},
        { code: '5169', name: 'Chemicals and Allied Products (Not Elsewhere Classified) u'},
        { code: '5172', name: 'Petroleum and Petroleum Products u'},
        { code: '5192', name: 'Books, Periodicals and Newspapers u'},
        { code: '5193', name: 'Florists Supplies, Nursery Stock and Flowers u'},
        { code: '5198', name: 'Paints, Varnishes and Supplies u'},
        { code: '5199', name: 'Nondurable Goods (Not Elsewhere Classified) u'},
        { code: '5200', name: 'Home Supply Warehouse Stores'},
        { code: '5211', name: 'Lumber and Building Materials Stores'},
        { code: '5231', name: 'Glass, Paint, and Wallpaper Stores'},
        { code: '5251', name: 'Hardware Stores'},
        { code: '5261', name: 'Nurseries and Lawn and Garden Supply Stores'},
        { code: '5271', name: 'Mobile Home Dealers'},
        { code: '5300', name: 'Wholesale Clubs'},
        { code: '5309', name: 'Duty Free Stores'},
        { code: '5310', name: 'Discount Stores'},
        { code: '5311', name: 'Department Stores'},
        { code: '5331', name: 'Variety Stores'},
        { code: '5399', name: 'Miscellaneous General Merchandise'},
        { code: '5411', name: 'Grocery Stores and Supermarkets'},
        { code: '5422', name: 'Freezer and Locker Meat Provisioners'},
        { code: '5441', name: 'Candy, Nut, and Confectionery Stores'},
        { code: '5451', name: 'Dairy Products Stores'},
        { code: '5462', name: 'Bakeries'},
        { code: '5499', name: 'Miscellaneous Food Stores - Convenience Stores and SpecialtyMarkets'},
        { code: '5511', name: 'Car and Truck Dealers (New/Used) Sales, Service, Repairs, Parts, Leasing'},
        { code: '5521', name: 'Car and Truck Dealers (Used Only) Sales, Service, Repairs, Parts, andLeasing'},
        { code: '5532', name: 'Automotive Tire Stores'},
        { code: '5533', name: 'Automotive Parts and Accessories Stores'},
        { code: '5541', name: 'Service Stations (With or without Ancillary Services)'},
        { code: '5542', name: 'Automated Fuel Dispensers'},
        { code: '5551', name: 'Boat Dealers'},
        { code: '5561', name: 'Camper, Recreational and Utility Trailer Dealers'},
        { code: '5571', name: 'Motorcycle Shops and Dealers'},
        { code: '5592', name: 'Motor Home Dealers'},
        { code: '5598', name: 'Snowmobile Dealers'},
        { code: '5599', name: 'Miscellaneous Automotive, Aircraft, and Farm Equipment Dealers(Not Elsewhere Classified)'},
        { code: '5611', name: 'Men\'s and Boys\' Clothing and Accessories Stores'},
        { code: '5621', name: 'Women\'s Ready-To-Wear Stores'},
        { code: '5631', name: 'Women\'s Accessory and Specialty Shops'},
        { code: '5641', name: 'Children\'s and Infants\' Wear Stores'},
        { code: '5651', name: 'Family Clothing Stores'},
        { code: '5655', name: 'Sports and Riding Apparel Stores'},
        { code: '5661', name: 'Shoe Stores'},
        { code: '5681', name: 'Furriers and Fur Shops'},
        { code: '5691', name: 'Men\'s and Women\'s Clothing Stores'},
        { code: '5697', name: 'Tailors, Seamstresses, Mending, and Alterations'},
        { code: '5698', name: 'Wig and Toupee Stores'},
        { code: '5699', name: 'Miscellaneous Apparel and Accessory Shops'},
        { code: '5712', name: 'Furniture, Home Furnishings and Equipment Stores, Except Appliances'},
        { code: '5713', name: 'Floor Covering Stores'},
        { code: '5714', name: 'Drapery, Window Covering, and Upholstery Stores'},
        { code: '5718', name: 'Fireplace, Fireplace Screens and Accessories Stores'},
        { code: '5719', name: 'Miscellaneous Home Furnishing Specialty Stores'},
        { code: '5722', name: 'Household Appliance Stores'},
        { code: '5732', name: 'Electronics Stores'},
        { code: '5733', name: 'Music Stores - Musical Instruments, Pianos, and Sheet Music'},
        { code: '5734', name: 'Computer Software Stores'},
        { code: '5735', name: 'Record Stores'},
        { code: '5811', name: 'Caterers'},
        { code: '5812', name: 'Eating Places and Restaurants'},
        { code: '5813', name: 'Drinking Places (Alcoholic Beverages) - Bars, Taverns, Nightclubs, Cocktail Lounges, and Discotheques'},
        { code: '5814', name: 'Fast Food Restaurants'},
        { code: '5815', name: 'Digital Goods Media - Books, Movies, Music'},
        { code: '5816', name: 'Digital Goods - Games'},
        { code: '5817', name: 'Digital Goods - Applications (Excludes Games)'},
        { code: '5818', name: 'Digital Goods - Large Digital Goods Merchant'},
        { code: '5912', name: 'Drug Stores and Pharmacies'},
        { code: '5921', name: 'Package Stores - Beer, Wine, and Liquor'},
        { code: '5931', name: 'Used Merchandise and Secondhand Stores'},
        { code: '5932', name: 'Antique Shops - Sales, Repairs, and Restoration Services'},
        { code: '5933', name: 'Pawn Shops'},
        { code: '5935', name: 'Wrecking and Salvage Yards'},
        { code: '5937', name: 'Antique Reproductions'},
        { code: '5940', name: 'Bicycle Shops - Sales and Service'},
        { code: '5941', name: 'Sporting Goods Stores'},
        { code: '5942', name: 'Book Stores'},
        { code: '5943', name: 'Stationery Stores, Office and School Supply Stores'},
        { code: '5944', name: 'Jewelry Stores, Watches, Clocks, and Silverware Stores'},
        { code: '5945', name: 'Hobby, Toy and Game Shops'},
        { code: '5946', name: 'Camera and Photographic Supply Stores'},
        { code: '5947', name: 'Gift, Card, Novelty and Souvenir Shops'},
        { code: '5948', name: 'Luggage and Leather Goods Stores'},
        { code: '5949', name: 'Sewing, Needlework, Fabric and Piece Goods Stores'},
        { code: '5950', name: 'Glassware/Crystal Stores'},
        { code: '5960', name: 'Direct Marketing - Insurance Services'},
        { code: '5962', name: 'Direct Marketing - Travel-Related Arrangement Services'},
        { code: '5963', name: 'Door-To-Door Sales'},
        { code: '5964', name: 'Direct Marketing - Catalog Merchant'},
        { code: '5965', name: 'Direct Marketing - Combination Catalog and Retail Merchant'},
        { code: '5966', name: 'Direct Marketing - Outbound Telemarketing Merchant'},
        { code: '5967', name: 'Direct Marketing - Inbound Teleservices Merchant'},
        { code: '5968', name: 'Direct Marketing - Continuity/Subscription Merchant'},
        { code: '5969', name: 'Direct Marketing - Other Direct Marketers(Not Elsewhere Classified)'},
        { code: '5970', name: 'Artist\'s Supply and Craft Shops'},
        { code: '5971', name: 'Art Dealers and Galleries'},
        { code: '5972', name: 'Stamp and Coin Stores'},
        { code: '5973', name: 'Religious Goods Stores'},
        { code: '5975', name: 'Hearing Aids - Sales, Service, and Supply'},
        { code: '5976', name: 'Orthopedic Goods - Prosthetic Devices'},
        { code: '5977', name: 'Cosmetic Stores'},
        { code: '5978', name: 'Typewriter Stores - Sales, Rentals, and Service'},
        { code: '5983', name: 'Fuel Dealers - Fuel Oil, Wood, Coal, and Liquefied Petroleum'},
        { code: '5992', name: 'Florists'},
        { code: '5993', name: 'Cigar Stores and Stands'},
        { code: '5994', name: 'News Dealers and Newsstands'},
        { code: '5995', name: 'Pet Shops, Pet Foods and Supplies Stores'},
        { code: '5996', name: 'Swimming Pools - Sales and Service'},
        { code: '5997', name: 'Electric Razor Stores - Sales and Service'},
        { code: '5998', name: 'Tent and Awning Shops'},
        { code: '5999', name: 'Miscellaneous and Specialty Retail Stores'},
        { code: '6010', name: 'Financial Institutions - Manual Cash Disbursements'},
        { code: '6011', name: 'Financial Institutions - Automated Cash Disbursements'},
        { code: '6012', name: 'Financial Institutions - Merchandise and Services'},
        { code: '6051', name: 'Non-Financial Institutions - Foreign Currency, Money Orders (Not Wire Transfer), Stored Value Card/Load, and Travelers Cheques'},
        { code: '6211', name: 'Security Brokers/Dealers'},
        { code: '6300', name: 'Insurance Sales, Underwriting, and Premiums'},
        { code: '6513', name: 'Real Estate Agents and Managers - Rentals'},
        { code: '7011', name: 'Lodging - Hotels, Motels, Resorts, Central Reservation Services(Not Elsewhere Classified)'},
        { code: '7012', name: 'Timeshares'},
        { code: '7032', name: 'Sporting and Recreational Camps'},
        { code: '7033', name: 'Trailer Parks and Campgrounds'},
        { code: '7210', name: 'Laundry, Cleaning, and Garment Services'},
        { code: '7211', name: 'Laundries - Family and Commercial'},
        { code: '7216', name: 'Dry Cleaners'},
        { code: '7217', name: 'Carpet and Upholstery Cleaning'},
        { code: '7221', name: 'Photographic Studios'},
        { code: '7230', name: 'Beauty and Barber Shops - Like Salons'},
        { code: '7251', name: 'Shoe Repair Shops, Shoe Shine Parlors, and Hat Cleaning Shops'},
        { code: '7261', name: 'Funeral Services and Crematories'},
        { code: '7273', name: 'Dating Services'},
        { code: '7276', name: 'Tax Preparation Services'},
        { code: '7277', name: 'Counseling Services - Debt, Marriage, and Personal'},
        { code: '7278', name: 'Buying and Shopping Services and Clubs'},
        { code: '7296', name: 'Clothing Rental - Costumes, Uniforms, Formal Wear'},
        { code: '7297', name: 'Massage Parlors'},
        { code: '7298', name: 'Health and Beauty Spas'},
        { code: '7299', name: 'Miscellaneous Personal Services (Not Elsewhere Classified) - Like animal boarding, bath houses, house sitting \
        services, maid services, pet grooming, animal grooming and kennels, animal training or \
        breeding, real estate agents, brokers, and managers, body piercing and \
        tattooing, water treatment services, taxidermists, wedding chapels, and animal \
        cremation and burial services\
        '},
        
        { code: '7311', name: 'Advertising Services'},
        { code: '7321', name: 'Consumer Credit Reporting Agencies'},
        { code: '7333', name: 'Commercial Photography, Art, and Graphics'},
        { code: '7338', name: 'Quick Copy, Reproduction, and Blueprinting Services'},
        { code: '7339', name: 'Stenographic and Secretarial Support'},
        { code: '7342', name: 'Exterminating and Disinfecting Services'},
        { code: '7349', name: 'Cleaning, Maintenance, and Janitorial Services'},
        { code: '7361', name: 'Employment Agencies and Temporary Help Services'},
        { code: '7372', name: 'Computer Programming, Data Processing, and Integrated Systems Design Services'},
        { code: '7375', name: 'Information Retrieval Services u'},
        { code: '7379', name: 'Computer Maintenance, Repair and Services (Not Elsewhere Classified) u'},
        { code: '7392', name: 'Management, Consulting, and Public Relations Services'},
        { code: '7393', name: 'Detective Agencies, Protective Agencies, and Security Services, including Armored Cars, and Guard Dogs'},
        { code: '7394', name: 'Equipment, Tool, Furniture, and Appliance Rental and Leasing'},
        { code: '7395', name: 'Photofinishing Laboratories and Photo Developing'},
        { code: '7399', name: 'Business Services (Not Elsewhere Classified)'},
        { code: '7512', name: 'Automobile Rental Agency'},
        { code: '7513', name: 'Truck and Utility Trailer Rentals'},
        { code: '7519', name: 'Motor Home and Recreational Vehicle Rentals'},
        { code: '7523', name: 'Parking Lots, Parking Meters and Garages'},
        { code: '7531', name: 'Automotive Body Repair Shops'},
        { code: '7534', name: 'Tire Retreading and Repair Shops'},
        { code: '7535', name: 'Automotive Paint Shops'},
        { code: '7538', name: 'Automotive Service Shops'},
        { code: '7542', name: 'Car Washes'},
        { code: '7549', name: 'Towing Services'},
        { code: '7622', name: 'Electronics Repair Shops'},
        { code: '7623', name: 'Air Conditioning and Refrigeration Repair Shops'},
        { code: '7629', name: 'Electrical and Small Appliance Repair Shops'},
        { code: '7631', name: 'Watch, Clock and Jewelry Repair'},
        { code: '7641', name: 'Furniture - Reupholstery, Repair, and Refinishing'},
        { code: '7692', name: 'Welding Services'},
        { code: '7699', name: 'Miscellaneous Repair Shops and Related Services'},
        { code: '7800', name: 'Government-Owned Lotteries'},
        { code: '7801', name: 'Government-Licensed On-Line Casinos (On-Line Gambling)'},
        { code: '7802', name: 'Government-Licensed Horse/Dog Racing'},
        { code: '7829', name: 'Motion Picture and Video Tape Production and Distribution u'},
        { code: '7832', name: 'Motion Picture Theaters'},
        { code: '7841', name: 'DVD/Video Tape Rental Stores'},
        { code: '7911', name: 'Dance Halls, Studios and Schools'},
        { code: '7922', name: 'Theatrical Producers (Except Motion Pictures) and Ticket Agencies'},
        { code: '7929', name: 'Bands, Orchestras, and Miscellaneous Entertainers (Not Elsewhere Classified)'},
        { code: '7932', name: 'Billiard and Pool Establishments'},
        { code: '7933', name: 'Bowling Alleys'},
        { code: '7941', name: 'Commercial Sports, Professional Sports Clubs, Athletic Fields, and Sports Promoters'},
        { code: '7991', name: 'Tourist Attractions and Exhibits'},
        { code: '7992', name: 'Public Golf Courses'},
        { code: '7993', name: 'Video Amusement Game Supplies'},
        { code: '7994', name: 'Video Game Arcades/Establishments'},
        { code: '7995', name: 'Betting, including Lottery Tickets, Casino Gaming Chips, Off-Track Betting, and Wagers at Race Tracks'},
        { code: '7996', name: 'Amusement Parks, Circuses, Carnivals, and Fortune Tellers'},
        { code: '7997', name: 'Membership Clubs (Sports, Recreation, Athletic), Country Clubs, and Private Golf Courses'},
        { code: '7998', name: 'Aquariums, Seaquariums, Dolphinariums, and Zoos'},
        { code: '7999', name: 'Recreation Services (Not Elsewhere Classified)'},
        { code: '8011', name: 'Doctors and Physicians (Not Elsewhere Classified)'},
        { code: '8021', name: 'Dentists and Orthodontists'},
        { code: '8031', name: 'Osteopaths'},
        { code: '8041', name: 'Chiropractors'},
        { code: '8042', name: 'Optometrists and Ophthalmologists'},
        { code: '8043', name: 'Opticians, Optical Goods, and Eyeglasses'},
        { code: '8049', name: 'Podiatrists and Chiropodists'},
        { code: '8050', name: 'Nursing and Personal Care Facilities'},
        { code: '8062', name: 'Hospitals'},
        { code: '8071', name: 'Medical and Dental Laboratories'},
        { code: '8099', name: 'Medical Services and Health Practitioners (Not Elsewhere Classified)'},
        { code: '8111', name: 'Legal Services and Attorneys'},
        { code: '8211', name: 'Elementary and Secondary Schools'},
        { code: '8220', name: 'Colleges, Universities, Professional Schools, and Junior Colleges'},
        { code: '8241', name: 'Correspondence Schools'},
        { code: '8244', name: 'Business and Secretarial Schools'},
        { code: '8249', name: 'Vocational and Trade Schools'},
        { code: '8299', name: 'Schools and Educational Services (Not Elsewhere Classified)'},
        { code: '8351', name: 'Child Care Services'},
        { code: '8398', name: 'Charitable and Social Service Organizations'},
        { code: '8641', name: 'Civic, Social, and Fraternal Associations'},
        { code: '8651', name: 'Political Organizations'},
        { code: '8661', name: 'Religious Organizations'},
        { code: '8675', name: 'Automobile Associations'},
        { code: '8699', name: 'Membership Organizations (Not Elsewhere Classified)'},
        { code: '8734', name: 'Testing Laboratories (Non-Medical Testing) u'},
        { code: '8911', name: 'Architectural, Engineering, and Surveying Services'},
        { code: '8931', name: 'Accounting, Auditing, and Bookkeeping Services'},
        { code: '8999', name: 'Professional Services (Not Elsewhere Classified)'},
        { code: '9211', name: 'Court Costs, Including Alimony and Child Support'},
        { code: '9222', name: 'Fines'},
        { code: '9223', name: 'Bail and Bond Payments'},
        { code: '9311', name: 'Tax Payments'},
        { code: '9399', name: 'Government Services (Not Elsewhere Classified)'},
        { code: '9402', name: 'Postal Services - Government Only'},
        { code: '9405', name: 'U.S. Federal Government Agencies or Departments'},
        { code: '9700', name: 'Automated Referral Service'},
        { code: '9702', name: 'Emergency Services (GCAS)'},
        { code: '9950', name: 'Intra-Company Purchases u'},
        ]; //end business MCC options
    },


};