export default {
    data() {
        return ({
            stockType: [
                {'value': 0, 'label': 'New for sale'},
                {'value': 1, 'label': 'Refurbished'},
                {'value': 2, 'label': 'damaged'},
                {'value': 3, 'label': 'New for internal use'},
            ],
            transactionType: [
                {'value': "RS", 'label': "Receive Stock"},
                {'value': "PS", 'label': "Product Sale"},
                {'value': "PR", 'label': "Product Return"},
                {'value': "AS", 'label': "Adjust Stock"},
                {'value': "CP", 'label': "Change Unit Price"},
                {'value': "SU", 'label': "Service Use"},
                {'value': "IU", 'label': "Inventory Count Update"},
            ],
            adjustType: [
                {'value': 1, 'label': 'Count Update'},
            ],
            resourceAttributeType: [
                {'value': 1, 'label': 'String'},
                {'value': 2, 'label': 'Number'},
                {'value': 3, 'label': 'Boolean'}
            ],
            resourceAccessType: [
                {'value': 1, 'label': 'Public (external)'},
                {'value': 2, 'label': 'Business (any staff usage)'},
                {'value': 3, 'label': 'Resource Owner Only'},
            ],
            
            classType: [
                {'value': '1', 'label': 'Class'},
                {'value': '2', 'label': 'Recurring Class'},
            ],
            classStatusType: [
                {'value': 'draft', 'label': 'Draft'},
                {'value': 'active', 'label': 'Active'},
                {'value': 'cancel', 'label': 'Cancel'}
            ],
            classLocationType: [
                {'value': 'Online', 'label': 'Online'},
                {'value': 'Offline', 'label': 'Offline'},
                {'value': 'Both', 'label': 'Both'}
            ],
            meetEveryType: [
                {'value': 'Day', 'label': 'Day'},
                {'value': 'Week', 'label': 'Week'},
                {'value': 'Month', 'label': 'Month'},
                {'value': 'Adhoc', 'label': 'Adhoc'}
            ],
            weekDays: [
                {'value': 'Sun', 'label': 'Sun'},
                {'value': 'Mon', 'label': 'Mon'},
                {'value': 'Tue', 'label': 'Tue'},
                {'value': 'Wed', 'label': 'Wed'},
                {'value': 'Thu', 'label': 'Thu'},
                {'value': 'Fri', 'label': 'Fri'},
                {'value': 'Sat', 'label': 'Sat'}
            ],
            classPaymentModeType: [
                {'value': 'per_class', 'label': 'Per Class'},
                {'value': 'flat_rate', 'label': 'Flat rate'}
            ],
            classInvoiceType: [
                {'value': 'Upfront', 'label': 'Upfront'},
                {'value': 'Monthly', 'label': 'Monthly'},
                {'value': 'Weekly', 'label': 'Weekly'},
                {'value': 'EachClass', 'label': 'EachClass'},
            ],
            bookingStatusType: [
                {'value': 'cancelled', 'label': 'Canceled'},
                {'value': 'scheduled', 'label': 'Scheduled'},
                {'value': 'completed', 'label': 'Completed'},
            ],
            classSignupStatusType: [
                {'value': 'payment_pending', 'label': 'Payment Pending'},
                {'value': 'confirm', 'label': 'Confirm'},
                {'value': 'waitlist', 'label': 'Waitlist'},
                {'value': 'drop', 'label': 'Drop'}
            ],
            classInstanceTrackerStatusType: [
                {'value': 'present', 'label': 'Present'},
                {'value': 'absent', 'label': 'Absent'}
            ],
            countryWithStateData: [
                {
                    "label": "US & Canada",
                    "states": [
                        { value:"AK", label: "Alaska" },
                        { value:"AL", label: "Alabama" },
                        { value:"AR", label: "Arkansas" },
                        { value:"AZ", label: "Arizona" },
                        { value:"CA", label: "California" },
                        { value:"CO", label: "Colorado" },
                        { value:"CT", label: "Connecticut" },
                        { value:"DC", label: "District of Columbia" },
                        { value:"DE", label: "Delaware" },
                        { value:"FL", label: "Florida" },
                        { value:"GA", label: "Georgia" },
                        { value:"HI", label: "Hawaii" },
                        { value:"IA", label: "Iowa" },
                        { value:"ID", label: "Idaho" },
                        { value:"IL", label: "Illinois" },
                        { value:"IN", label: "Indiana" },
                        { value:"KS", label: "Kansas" },
                        { value:"KY", label: "Kentucky" },
                        { value:"LA", label: "Louisiana" },
                        { value:"MA", label: "Massachusetts" },
                        { value:"MD", label: "Maryland" },
                        { value:"ME", label: "Maine" },
                        { value:"MI", label: "Michigan" },
                        { value:"MN", label: "Minnesota" },
                        { value:"MO", label: "Missouri" },
                        { value:"MS", label: "Mississippi" },
                        { value:"MT", label: "Montana" },
                        { value:"NC", label: "North Carolina" },
                        { value:"ND", label: "North Dakota" },
                        { value:"NE", label: "Nebraska" },
                        { value:"NH", label: "New Hampshire" },
                        { value:"NJ", label: "New Jersey" },
                        { value:"NM", label: "New Mexico" },
                        { value:"NV", label: "Nevada" },
                        { value:"NY", label: "New York" },
                        { value:"OH", label: "Ohio" },
                        { value:"OK", label: "Oklahoma" },
                        { value:"OR", label: "Oregon" },
                        { value:"PA", label: "Pennsylvania" },
                        { value:"PR", label: "Puerto Rico" },
                        { value:"RI", label: "Rhode Island" },
                        { value:"SC", label: "South Carolina" },
                        { value:"SD", label: "South Dakota" },
                        { value:"TN", label: "Tennessee" },
                        { value:"TX", label: "Texas" },
                        { value:"UT", label: "Utah" },
                        { value:"VA", label: "Virginia" },
                        { value:"VT", label: "Vermont" },
                        { value:"WA", label: "Washington" },
                        { value:"WI", label: "Wisconsin" },
                        { value:"WV", label: "West Virginia" },
                        { value:"WY", label: "Wyoming" },
                        { value: "AB", label: "Alberta" },
                        { value: "BC", label: "British Columbia" },
                        { value: "MB", label: "Manitoba" },
                        { value: "NB", label: "New Brunswick" },
                        { value: "NF", label: "Newfoundland" },
                        { value: "NT", label: "Northwest Territories" },
                        { value: "NS", label: "Nova Scotia" },
                        { value: "NU", label: "Nunavut" },
                        { value: "ON", label: "Ontario" },
                        { value: "PE", label: "Prince Edward Island" },
                        { value: "QC", label: "Quebec" },
                        { value: "SK", label: "Saskatchewan" },
                        { value: "YT", label: "Yukon Territory" }
                    ]
                },
                {
                    "label": "UK",
                    "states": [
                        { value: "LND", label: "London, City of" },
                        { value: "ABE", label: "Aberdeen City" },
                        { value: "ABD", label: "Aberdeenshire" },
                        { value: "ANS", label: "Angus" },
                        { value: "AGB", label: "Argyll and Bute" },
                        { value: "CLK", label: "Clackmannanshire" },
                        { value: "DGY", label: "Dumfries and Galloway" },
                        { value: "DND", label: "Dundee City" },
                        { value: "EAY", label: "East Ayrshire" },
                        { value: "EDU", label: "East Dunbartonshire" },
                        { value: "ELN", label: "East Lothian" },
                        { value: "ERW", label: "East Renfrewshire" },
                        { value: "EDH", label: "Edinburgh, City of" },
                        { value: "ELS", label: "Eilean Siar" },
                        { value: "FAL", label: "Falkirk" },
                        { value: "FIF", label: "Fife" },
                        { value: "GLG", label: "Glasgow City" },
                        { value: "HLD", label: "Highland" },
                        { value: "IVC", label: "Inverclyde" },
                        { value: "MLN", label: "Midlothian" },
                        { value: "MRY", label: "Moray" },
                        { value: "NAY", label: "North Ayrshire" },
                        { value: "NLK", label: "North Lanarkshire" },
                        { value: "ORK", label: "Orkney Islands" },
                        { value: "PKN", label: "Perth and Kinross" },
                        { value: "RFW", label: "Renfrewshire" },
                        { value: "SCB", label: "Scottish Borders" },
                        { value: "ZET", label: "Shetland Islands" },
                        { value: "SAY", label: "South Ayrshire" },
                        { value: "SLK", label: "South Lanarkshire" },
                        { value: "STG", label: "Stirling" },
                        { value: "WDU", label: "West Dunbartonshire" },
                        { value: "WLN", label: "West Lothian" },
                        { value: "ANN", label: "Antrim and Newtownabbey" },
                        { value: "AND", label: "Ards and North Down" },
                        { value: "ABC", label: "Armagh City, Banbridge and Craigavon" },
                        { value: "BFS", label: "Belfast City" },
                        { value: "CCG", label: "Causeway Coast and Glens" },
                        { value: "DRS", label: "Derry and Strabane" },
                        { value: "FMO", label: "Fermanagh and Omagh" },
                        { value: "LBC", label: "Lisburn and Castlereagh" },
                        { value: "MEA", label: "Mid and East Antrim" },
                        { value: "MUL", label: "Mid-Ulster" },
                        { value: "NMD", label: "Newry, Mourne and Down" },
                        { value: "BDG", label: "Barking and Dagenham" },
                        { value: "BNE", label: "Barnet" },
                        { value: "BEX", label: "Bexley" },
                        { value: "BEN", label: "Brent" },
                        { value: "BRY", label: "Bromley" },
                        { value: "CMD", label: "Camden" },
                        { value: "CRY", label: "Croydon" },
                        { value: "EAL", label: "Ealing" },
                        { value: "ENF", label: "Enfield" },
                        { value: "GRE", label: "Greenwich" },
                        { value: "HCK", label: "Hackney" },
                        { value: "HMF", label: "Hammersmith and Fulham" },
                        { value: "HRY", label: "Haringey" },
                        { value: "HRW", label: "Harrow" },
                        { value: "HAV", label: "Havering" },
                        { value: "HIL", label: "Hillingdon" },
                        { value: "HNS", label: "Hounslow" },
                        { value: "ISL", label: "Islington" },
                        { value: "KEC", label: "Kensington and Chelsea" },
                        { value: "KTT", label: "Kingston upon Thames" },
                        { value: "LBH", label: "Lambeth" },
                        { value: "LEW", label: "Lewisham" },
                        { value: "MRT", label: "Merton" },
                        { value: "NWM", label: "Newham" },
                        { value: "RDB", label: "Redbridge" },
                        { value: "RIC", label: "Richmond upon Thames" },
                        { value: "SWK", label: "Southwark" },
                        { value: "STN", label: "Sutton" },
                        { value: "TWH", label: "Tower Hamlets" },
                        { value: "WFT", label: "Waltham Forest" },
                        { value: "WND", label: "Wandsworth" },
                        { value: "WSM", label: "Westminster" },
                        { value: "BNS", label: "Barnsley" },
                        { value: "BIR", label: "Birmingham" },
                        { value: "BOL", label: "Bolton" },
                        { value: "BRD", label: "Bradford" },
                        { value: "BUR", label: "Bury" },
                        { value: "CLD", label: "Calderdale" },
                        { value: "COV", label: "Coventry" },
                        { value: "DNC", label: "Doncaster" },
                        { value: "DUD", label: "Dudley" },
                        { value: "GAT", label: "Gateshead" },
                        { value: "KIR", label: "Kirklees" },
                        { value: "KWL", label: "Knowsley" },
                        { value: "LDS", label: "Leeds" },
                        { value: "LIV", label: "Liverpool" },
                        { value: "MAN", label: "Manchester" },
                        { value: "NET", label: "Newcastle upon Tyne" },
                        { value: "NTY", label: "North Tyneside" },
                        { value: "OLD", label: "Oldham" },
                        { value: "RCH", label: "Rochdale" },
                        { value: "ROT", label: "Rotherham" },
                        { value: "SLF", label: "Salford" },
                        { value: "SAW", label: "Sandwell" },
                        { value: "SFT", label: "Sefton" },
                        { value: "SHF", label: "Sheffield" },
                        { value: "SOL", label: "Solihull" },
                        { value: "STY", label: "South Tyneside" },
                        { value: "SHN", label: "St. Helens" },
                        { value: "SKP", label: "Stockport" },
                        { value: "SND", label: "Sunderland" },
                        { value: "TAM", label: "Tameside" },
                        { value: "TRF", label: "Trafford" },
                        { value: "WKF", label: "Wakefield" },
                        { value: "WLL", label: "Walsall" },
                        { value: "WGN", label: "Wigan" },
                        { value: "WRL", label: "Wirral" },
                        { value: "WLV", label: "Wolverhampton" },
                        { value: "BKM", label: "Buckinghamshire" },
                        { value: "CAM", label: "Cambridgeshire" },
                        { value: "CMA", label: "Cumbria" },
                        { value: "DBY", label: "Derbyshire" },
                        { value: "DEV", label: "Devon" },
                        { value: "DOR", label: "Dorset" },
                        { value: "ESX", label: "East Sussex" },
                        { value: "ESS", label: "Essex" },
                        { value: "GLS", label: "Gloucestershire" },
                        { value: "HAM", label: "Hampshire" },
                        { value: "HRT", label: "Hertfordshire" },
                        { value: "KEN", label: "Kent" },
                        { value: "LAN", label: "Lancashire" },
                        { value: "LEC", label: "Leicestershire" },
                        { value: "LIN", label: "Lincolnshire" },
                        { value: "NFK", label: "Norfolk" },
                        { value: "NYK", label: "North Yorkshire" },
                        { value: "NTH", label: "Northamptonshire" },
                        { value: "NTT", label: "Nottinghamshire" },
                        { value: "OXF", label: "Oxfordshire" },
                        { value: "SOM", label: "Somerset" },
                        { value: "STS", label: "Staffordshire" },
                        { value: "SFK", label: "Suffolk" },
                        { value: "SRY", label: "Surrey" },
                        { value: "WAR", label: "Warwickshire" },
                        { value: "WSX", label: "West Sussex" },
                        { value: "WOR", label: "Worcestershire" },
                        { value: "BAS", label: "Bath and North East Somerset" },
                        { value: "BDF", label: "Bedford" },
                        { value: "BBD", label: "Blackburn with Darwen" },
                        { value: "BPL", label: "Blackpool" },
                        { value: "BGW", label: "Blaenau Gwent" },
                        { value: "BCP", label: "Bournemouth, Christchurch and Poole" },
                        { value: "BRC", label: "Bracknell Forest" },
                        { value: "BGE", label: "Bridgend [Pen-y-bont ar Ogwr GB-POG]" },
                        { value: "BNH", label: "Brighton and Hove" },
                        { value: "BST", label: "Bristol, City of" },
                        { value: "CAY", label: "Caerphilly [Caerffili GB-CAF]" },
                        { value: "CRF", label: "Cardiff [Caerdydd GB-CRD]" },
                        { value: "CMN", label: "Carmarthenshire [Sir Gaerfyrddin GB-GFY]" },
                        { value: "CBF", label: "Central Bedfordshire" },
                        { value: "CGN", label: "Ceredigion [Sir Ceredigion]" },
                        { value: "CHE", label: "Cheshire East" },
                        { value: "CHW", label: "Cheshire West and Chester" },
                        { value: "CWY", label: "Conwy" },
                        { value: "CON", label: "Cornwall" },
                        { value: "DAL", label: "Darlington" },
                        { value: "DEN", label: "Denbighshire [Sir Ddinbych GB-DDB]" },
                        { value: "DER", label: "Derby" },
                        { value: "DUR", label: "Durham, County" },
                        { value: "ERY", label: "East Riding of Yorkshire" },
                        { value: "FLN", label: "Flintshire [Sir y Fflint GB-FFL]" },
                        { value: "GWN", label: "Gwynedd" },
                        { value: "HAL", label: "Halton" },
                        { value: "HPL", label: "Hartlepool" },
                        { value: "HEF", label: "Herefordshire" },
                        { value: "AGY", label: "Isle of Anglesey [Sir Ynys Môn GB-YNM]" },
                        { value: "IOW", label: "Isle of Wight" },
                        { value: "IOS", label: "Isles of Scilly" },
                        { value: "KHL", label: "Kingston upon Hull" },
                        { value: "LCE", label: "Leicester" },
                        { value: "LUT", label: "Luton" },
                        { value: "MDW", label: "Medway" },
                        { value: "MTY", label: "Merthyr Tydfil [Merthyr Tudful GB-MTU]" },
                        { value: "MDB", label: "Middlesbrough" },
                        { value: "MIK", label: "Milton Keynes" },
                        { value: "MON", label: "Monmouthshire [Sir Fynwy GB-FYN]" },
                        { value: "NTL", label: "Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]" },
                        { value: "NWP", label: "Newport [Casnewydd GB-CNW]" },
                        { value: "NEL", label: "North East Lincolnshire" },
                        { value: "NLN", label: "North Lincolnshire" },
                        { value: "NSM", label: "North Somerset" },
                        { value: "NBL", label: "Northumberland" },
                        { value: "NGM", label: "Nottingham" },
                        { value: "PEM", label: "Pembrokeshire [Sir Benfro GB-BNF]" },
                        { value: "PTE", label: "Peterborough" },
                        { value: "PLY", label: "Plymouth" },
                        { value: "POR", label: "Portsmouth" },
                        { value: "POW", label: "Powys" },
                        { value: "RDG", label: "Reading" },
                        { value: "RCC", label: "Redcar and Cleveland" },
                        { value: "RCT", label: "Rhondda Cynon Taff [Rhondda CynonTaf]" },
                        { value: "RUT", label: "Rutland" },
                        { value: "SHR", label: "Shropshire" },
                        { value: "SLG", label: "Slough" },
                        { value: "SGC", label: "South Gloucestershire" },
                        { value: "STH", label: "Southampton" },
                        { value: "SOS", label: "Southend-on-Sea" },
                        { value: "STT", label: "Stockton-on-Tees" },
                        { value: "STE", label: "Stoke-on-Trent" },
                        { value: "SWA", label: "Swansea [Abertawe GB-ATA]" },
                        { value: "SWD", label: "Swindon" },
                        { value: "TFW", label: "Telford and Wrekin" },
                        { value: "THR", label: "Thurrock" },
                        { value: "TOB", label: "Torbay" },
                        { value: "TOF", label: "Torfaen [Tor-faen]" },
                        { value: "VGL", label: "Vale of Glamorgan, The [Bro Morgannwg GB-BMG]" },
                        { value: "WRT", label: "Warrington" },
                        { value: "WBK", label: "West Berkshire" },
                        { value: "WIL", label: "Wiltshire" },
                        { value: "WNM", label: "Windsor and Maidenhead" },
                        { value: "WOK", label: "Wokingham" },
                        { value: "WRX", label: "Wrexham [Wrecsam GB-WRC]" },
                        { value: "YOR", label: "York" }
                    ]
                }
            ],
        });
    },
    methods: {
        getLabelStr(arrName, value) {
            if (!this[arrName]) {
                return null;
            }
            let searchedItem = this[arrName].find(t => t.value == value);
            return searchedItem ? searchedItem.label : null;
        }
    }
}